### ISSUE TITLE
Logout doesn't work, when application created by Okta-cli tool

### ISSUE THREAD

**Issue by KostiantynDrozd-okta** [okta-samples/okta-vue-sample#2]
Create application by command `okta start`.
Start application and perform login.

Click on 'Logout' button.

See attachment

<img width="1083" alt="Screen Shot 2020-11-13 at 12 39 00 PM" src="https://user-images.githubusercontent.com/70781392/99063605-66406c00-25ad-11eb-82da-0c113d96ea7d.png">

**Comment by mraible** [comment]
I can confirm this happens. Fixed in #4.
